# Generated by Django 4.1.4 on 2022-12-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
