# Generated by Django 4.1.4 on 2022-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='genre',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Historical', 'Historical'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Enter Author Name'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='bookname',
            field=models.CharField(max_length=50, verbose_name='Enter BookName'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Enter Email Id'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='price',
            field=models.IntegerField(help_text='You can also specify the approximate price', verbose_name='Enter Book Price'),
        ),
    ]
