# Generated by Django 4.1.4 on 2022-12-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_favbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favbooks',
            name='image',
            field=models.TextField(),
        ),
    ]
